board/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.post, name='post'),
    path('logout/', views.logoutUser, name='logout'),
    path('all/', views.all, name='all'),
    path('manage/', views.manage, name='manage'),
    path('manage/push/', views.push, name='push'),
    path('manage/push/pipeline/', views.pipeline, name='pipeline'),
]

potato/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import logout

urlpatterns = [
    path('', include('board.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('logout/', include('board.urls'), name='logout'),
    path('<int:post_id>/', include('board.urls')),
    path('all/', include('board.urls')),
    path('manage/', include('board.urls')),
    path('manage/push/', include('board.urls')),
    path('manage/push/pipeline/', include('board.urls')),
    path('admin/', admin.site.urls),
]

board/models.py
import uuid
import os

from django.db import models
from django import forms
from django.forms import ModelForm
from django.conf import settings
from django.utils.timezone import now
from .subjects import Subject
from django.contrib.auth.models import User

# help_text attributes are customised for TYSK, you will need to change them on an external deploy

class Post(models.Model):
    def file_path(instance, filename):
        extension = filename.split('.')[-1]
        filename = "%s.%s" % (uuid.uuid4(), extension)
        return os.path.join('i', filename)

    subject = models.CharField(max_length=3, choices=Subject.SUBJECT_SELECTABLES, default='NAS', help_text='"Other" or "Meta" will not provide a title automatically to any post you push')
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, editable=False, on_delete=models.CASCADE, null=True) # set to null=False for prod - should catch any hackers who bypass auth ig

    CHANNEL_SELECTABLES = (
        ('MAIN', 'Main channel'),
        ('LOWP', 'Low Priority'),
        ('META', 'Meta'),
    )

    channel = models.CharField(max_length=4, choices=CHANNEL_SELECTABLES, default='MAIN', help_text='Should this model be pushed to Main channel, Low Priority or Meta?')
    title = models.CharField(max_length=2000, help_text='e.g English Extension 1, Athletics Carnival - leave blank if using anything other than "Weekly Summary", "Other" or "Meta".')
    content = models.TextField(max_length=2000, help_text='supports GitHub-flavoured Markdown, see markdownguide.org/cheat-sheet. Not all Markdown elements (headings, horizontal line, tables) will render correctly, so stick to Discord-supported formatting please :)')
    file = models.FileField(upload_to=file_path, blank=True, null=True)
    location = models.CharField(max_length=2000, blank=True, help_text='e.g Blue Gym, W301, Sydney Olympic Park (Google Calendar only)') # Google Calendar only
    date = models.DateField(editable=True, blank=True, help_text='DD/MM/YYYY - e.g assignment due date/event date. Can be left blank. (Google Calendar and TYSK App only)', null=True) # Google Calendar and TYSK App only
    important = models.BooleanField(default=False, help_text='this will produce an @everyone ping on Discord and move a post to the Important channel on TYSK App') # this will produce an @everyone ping
    push_to_gcal = models.BooleanField(default=False, help_text='do you want to push this announcement to TYSK SubCal as well?') # this will produce an @everyone ping
    date_created = models.DateTimeField(default=now, editable=False)
    date_modified = models.DateTimeField(default=now, editable=False)

    # sword art online 2022 !!

# https://stackoverflow.com/a/2677474/6299634
class PostFile(models.Model):
    def file_path(instance, filename):
        extension = filename.split('.')[-1]
        filename = "%s.%s" % (uuid.uuid4(), extension)
        return os.path.join('i', filename)
    file = models.FileField(upload_to=file_path)

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

class Information(models.Model):
    info_contents = models.CharField(max_length=20000)
    manage_contents = models.CharField(max_length=20000)
    date_modified = models.DateField(default=now, editable=True)

class Emergency(models.Model):
    EMERGENCY_SELECTABLES = (
        ('1', 'info'),
        ('2', 'warning'),
        ('3', 'danger'),
    ) # directly linked to Bootstrap class names because I'm a monster

    message = models.CharField(max_length=2000, default='')
    priority = models.CharField(max_length=4, choices=EMERGENCY_SELECTABLES, default='1')
    enabled = models.BooleanField() # is this even enabled?
    date_created = models.DateField(default=now, editable=True)

"""
python manage.py makemigrations && python manage.py migrate
"""

board/views.py
from django.shortcuts import render
from django.template import loader
from django.http import Http404, HttpResponse, HttpResponseRedirect
from .models import Post, PostForm, Emergency, Information
from django.contrib.auth import logout
import environ

env = environ.Env(
    DEBUG=(bool, False)
)

environ.Env.read_env()

ROOT_URL = env('ROOT_URL')

def index(request):
    post_list = Post.objects.order_by('-date_created')[:10]
    post_list_all = Post.objects.order_by('-date_created')
    emergency = Emergency.objects.order_by('-date_created')[0]   # this will find the most recent iteration of the emergency msg
    infotext = Information.objects.order_by('-date_modified')[:1] # again, this will find the most recent iteration of infotext. Not really neccessary since we aren't iterating over the db anyway, but still a safe-to-have. [0] doesn't work since Emergency object is not iterable.
    url = ROOT_URL
    template = loader.get_template('board/index.html')
    context = {
        'url': url if request.user.is_authenticated else [],
        'post_list': post_list if request.user.is_authenticated else [],
        'infotext': infotext if request.user.is_authenticated else [],
        'emergency': emergency if request.user.is_authenticated else [],
    }
    return render(request, 'board/index.html', context)

def all(request):
    post_list_all = Post.objects.order_by('-date_created')
    emergency = Emergency.objects.order_by('-date_created')[0]
    template = loader.get_template('board/all.html')
    url = ROOT_URL
    context = {
        'url': url if request.user.is_authenticated else [],
        'post_list_all': post_list_all if request.user.is_authenticated else [],
        'emergency': emergency if request.user.is_authenticated else [],
    }
    return render(request, 'board/all.html', context)

def post(request, post_id):
    try:
        post = Post.objects.get(pk=post_id)
    except Post.DoesNotExist:
        raise Http404(NOT_FOUND_ERROR)
    url = ROOT_URL
    template = loader.get_template('board/post.html')
    emergency = Emergency.objects.order_by('-date_created')[0]
    context = {
        'post': post if request.user.is_authenticated else [],
        'url': url if request.user.is_authenticated else [],
        'emergency': emergency if request.user.is_authenticated else [],
    }
    return render(request, 'board/post.html', context)

def manage(request):
    url = ROOT_URL
    infotext = Information.objects.order_by('-date_modified')[:1]
    emergency = Emergency.objects.order_by('-date_created')[0]
    template = loader.get_template('board/manage.html')
    context = {
        'url': url if request.user.is_authenticated else [],
        'infotext': infotext if request.user.is_authenticated else [],
        'emergency': emergency if request.user.is_authenticated else [],
    }
    return render(request, 'board/manage.html', context)

def push(request):                          # https://docs.djangoproject.com/en/3.1/topics/forms/#the-view
    if request.method == 'POST':            # test whether this is a POST method request => process form data
        form = PostForm(request.POST)       # create form instance => populate with form data
        if form.is_valid():                 # validation
            p = form.save()
            p.content = form.cleaned_data['content']
            p.save()
            return HttpResponseRedirect('/manage/push/pipeline/')
    else: # if its a GET method then we create a blank form
        form = PostForm()
    context = {
        'form': form if request.user.is_authenticated else [],
    }
    return render(request, 'board/push.html', context)

def pipeline(request):
    post = Post.objects.order_by('-date_created')[0]
    context = {
        'post': post if request.user.is_authenticated else [],
    }
    return render(request, 'board/pipeline.html', context)

def logoutUser(request):
    logout(request)
    context = {}
    return render(request, 'board/logout.html', context)


def pipeline(request):
    post = Post.objects.order_by('-date_created')[0]
    context = {
        'post': post if request.user.is_authenticated else [],
    }
    return render(request, 'board/pipeline.html', context)

board/templates/board/all.html
<!doctype html>
<html class="no-js" lang="en-AU">

<!-- Find PotatoBoard at https://github.com/aidswidjaja/potatoboard-->
<!-- open source and everything under the MIT License! 2020-2021 (c) aidswidjaja -->

<head>
    <title>All posts | TYSK</title>
    {% include "board/head.html" %}
</head>

<body>

    {% include "board/init.html" %}

    {% if post_list_all %}
    <h2 class="mb-3 ms-3 me-3">every single post, ever!</h2>
    {% for post in post_list_all %}
    <div class="main-content">
        <div class="card mb-3 ms-3 me-3 post-card">
            <div class="card-header">
                <h6 class="text-uppercase subject-heading">{{ post.get_subject_display }}</h6>
            </div>
            <div class="card-body">
                <p class="card-text">
                <p class="post-card-text" id="{{ post.id }}"></p>
                <script>
                    var element = document.getElementById('{{ post.id }}');
                    content = marked('{{ post.content|linebreaksbr }}');
                    element.insertAdjacentHTML('afterbegin', content);
                // $clamp(element, {clamp: 3, useNativeClamp: true,});
                // see https://github.com/aidswidjaja/PotatoBoard/issues/1
                </script>
                <br>
                </p>
                <h6>
                    {% if post.channel == "MAIN" %}
                    <span class="badge badge-primary" style="background-color: #0070FF;">Main channel</span>
                    {% endif %}
                    {% if post.channel == "LOWP" %}
                    <span class="badge badge-primary" style="background-color: #FFBE00; color: #000000;">Low
                        priority</span>
                    {% endif %}
                    {% if post.channel == "META" %}
                    <span class="badge badge-primary" style="background-color: #008A4F;">Meta update</span>
                    {% endif %}
                    {% if post.important %}
                    <span class="badge badge-primary" style="background-color: #FF0000;">Important</span>
                    {% endif %}
                    <span class="inline-options-container">
                        <a class="inline-options clipboard-handler" id="tooltip{{ post.id }}"
                            data-clipboard-text="https://{{ url }}/{{ post.id}}/">permalink</a>
                        &nbsp;
                        <a class="inline-options" href="../{{ post.id }}">see details >></a>
                    </span>
                </h6>
            </div>
        </div>
        {% endfor %}
        <p class="mb-3 me-3 ms-3" style="color:#8C9095; font-weight: bold;">the beginning of everything</p>
        {% else %}
        {% endif %}
    </div>



</body>

{% include "board/footer.html" %}

</html>

board/templates/board/footer.html
<!-- Find PotatoBoard at https://github.com/aidswidjaja/potatoboard-->
<!-- open source and everything under the MIT License! 2020-2021 (c) aidswidjaja -->

<!-- using PotatoBoard outside of TYSK? you'll need to replace some of the hardcoded strings in this file then -->

<nav class="navbar navbar-light" style="background-color: #E1E1E1">
    <div class="container-fluid footer">
        <span class="mb-0 nav-link disabled"><strong>Need help? Email <a
                href="mailto:tysk@adrian.id.au?subject=Enquiry%20(PotatoBoard)&body=Name%3A%0D%0ADiscord%2FInstagram%2FWhatsApp%20(optional)%3A%0D%0AUser%2FStaff%3F%3A%0D%0A%0D%0AYour%20enquiry%3A%0D%0A">tysk@adrian.id.au</a></strong>
        </span>
        <span class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">indev</a>
            <!-- see issue #5 on GitHub -->
    </div>
</nav>

board/templates/board/head.html
<!-- Find PotatoBoard at https://github.com/aidswidjaja/potatoboard-->
<!-- open source and everything under the MIT License! 2020-2021 (c) aidswidjaja -->

<!-- using PotatoBoard outside of TYSK? you'll need to replace some of the hardcoded strings in this file then -->

<meta charset="utf-8">
<title>Things You Should Know</title>
<meta name="description"
    content="A free information service for Year 10 Aloys students to keep up-to-date with important events, assessments, and anything school related.">
<meta name="author" content="aidswidjaja">
<meta name="viewport" content="width=device-width, initial-scale=1">

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">

<!-- Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous"></script>

<!-- Twemoji -->
<!-- todo: figure out this emoji -->
<!-- <script src="https://twemoji.maxcdn.com/v/latest/twemoji.min.js" crossorigin="anonymous"></script> -->

<!--DOMPurify -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/dompurify/2.2.6/purify.min.js"
    integrity="sha512-rXAHWSMciPq2KsOxTvUeYNBb45apbcEXUVSIexVPOBnKfD/xo99uUe5M2OOsC49hGdUrkRLYsATkQQHMzUo/ew=="
    crossorigin="anonymous"></script>

<!-- Marked -->
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>

<!-- clamp-js-main -->
<!-- <script src="https://cdn.jsdelivr.net/npm/clamp-js-main@0.11.6/clamp.min.js"></script> -->
<!-- see https://github.com/aidswidjaja/PotatoBoard/issues/1 -->

<!-- clipboard.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js"></script>

<link rel="icon" type="image/png" href="favicon.png" />

<meta name="theme-color" content="#fafafa">

board/templates/board/index.html
<!doctype html>
<html class="no-js" lang="en-AU">

<!-- Find PotatoBoard at https://github.com/aidswidjaja/potatoboard-->
<!-- open source and everything under the MIT License! 2020-2021 (c) aidswidjaja -->

<head>
    <title>Home | TYSK</title>
    {% include "board/head.html" %}
</head>

<body>

    {% include "board/init.html" %}

    {% if user.is_authenticated %}
    
    {% for information in infotext %}
    <div class="body-container">
        <div class="card d-flex info-sidebar">
            <div class="card-body" id="info-container">
                <script>
                    var element = document.getElementById('info-container');
                    content = marked('{{ information.info_contents }}');
                    element.insertAdjacentHTML('afterbegin', content);
                </script>
            </div>
        </div>
    {% endfor %}
    {% else %}
    {% endif %}

        {% if post_list %}
        {% for post in post_list %}
        <div class="main-content">
            <div class="card mb-3 ms-3 me-3 post-card">
                <div class="card-header">
                    <h6 class="text-uppercase subject-heading">{{ post.get_subject_display }}</h6>
                </div>
                <div class="card-body">
                    <h5>{{ post.title }}</h5>
                    <p class="card-text">
                    <p class="post-card-text" id="{{ post.id }}"></p>
                    <script>
                        var element = document.getElementById('{{ post.id }}');
                        content = marked('{{ post.content|linebreaksbr }}');
                        element.insertAdjacentHTML('beforeend', content);
                // $clamp(element, {clamp: 3, useNativeClamp: true,});
                // see https://github.com/aidswidjaja/PotatoBoard/issues/1
                    </script>
                    <br>
                    </p>
                    <h6>
                        {% if post.channel == "MAIN" %}
                        <span class="badge badge-primary" style="background-color: #0070FF;">Main channel</span>
                        {% endif %}
                        {% if post.channel == "LOWP" %}
                        <span class="badge badge-primary" style="background-color: #FFBE00; color: #000000;">Low
                            priority</span>
                        {% endif %}
                        {% if post.channel == "META" %}
                        <span class="badge badge-primary" style="background-color: #008A4F;">Meta update</span>
                        {% endif %}
                        {% if post.important %}
                        <span class="badge badge-primary" style="background-color: #FF0000;">Important</span>
                        {% endif %}
                        <span class="inline-options-container">
                            <a class="inline-options clipboard-handler" id="tooltip{{ post.id }}"
                                data-clipboard-text="https://{{ url }}/{{ post.id}}/">permalink</a>
                            &nbsp;
                            <a class="inline-options" href="{{ post.id }}">see details >></a>
                        </span>
                    </h6>
                </div>
            </div>
            {% endfor %}
            <div class="card mb-3 ms-3 me-3 post-card">
                <div class="card-footer">
                    <p><code>you're currently seeing the 10 most recent posts. <a href="all/">see every post EVER!</a> warning: this may kill your computer</code>
                    </p>
                </div>
            </div>
            {% else %}
            {% endif %}

        </div>
    </div>

</body>

{% include "board/footer.html" %}

</html>

board/templates/board/init.html
<!-- Find PotatoBoard at https://github.com/aidswidjaja/potatoboard-->
<!-- open source and everything under the MIT License! 2020-2021 (c) aidswidjaja -->

<!-- using PotatoBoard outside of TYSK? you'll need to replace some of the hardcoded strings in this file then -->

{% load static %}

<script src="{% static 'init.js' %}"></script>

{% if emergency.enabled %}
<div class="alert alert-{{ emergency.get_priority_display }}" role="alert">
    <strong>{{ emergency.date_created }}: </strong>{{ emergency.message }}
</div>
{% endif %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" style="font-weight: bold" href="/">TYSK PotatoBoard</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://tysk.adrian.id.au">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/manage">Manage</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/admin">Admin</a>
                </li>
            </ul>
            <form class="d-flex">
                <!-- SEARCH FUNCTION START -->
                <input class="form-control me-2" type="search" placeholder="Search PotatoBoard (Placeholder)" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
                <!-- SEARCH FUNCTION END   -->
            </form>
        </div>
    </div>
</nav>
<br>

{% if user.is_authenticated %}
{% else %}
<div class="mb-3 ms-3 me-3">
    <p></p>
    Welcome to TYSK PotatoBoard! Please sign in with your school email address :D
    <br><br>
    <p><a class="btn btn-primary" href="{% url 'social:begin' 'google-oauth2' %}">
            Login
        </a></p>
</div>

{% endif %}

board/templates/board/logout.html
<!doctype html>
<html class="no-js" lang="en-AU">

<!-- Find PotatoBoard at https://github.com/aidswidjaja/potatoboard-->
<!-- open source and everything under the MIT License! 2020-2021 (c) aidswidjaja -->

<head>
    <title>Logged out successfully | TYSK</title>
    {% include "board/head.html" %}
    <style>
        label {
            font-size: 1.2rem;
        }

        tr {
            border-top: 30px solid;
            border-bottom: 30px solid;
            border-color: transparent;
        }
    </style>
</head>

<body>
    {% include "board/init.html" %}

    <p>You have logged out.</p>
    <p><a class="btn btn-primary" href="{% url 'social:begin' 'google-oauth2' %}">
        Login
    </a></p>
</body>

{% include "board/footer.html" %}

</html>

board/templates/board/manage.html
<!doctype html>
<html class="no-js" lang="en-AU">

<!-- Find PotatoBoard at https://github.com/aidswidjaja/potatoboard-->
<!-- open source and everything under the MIT License! 2020-2021 (c) aidswidjaja -->

<head>
    <title>Manage | TYSK</title>
    {% include "board/head.html" %}
</head>

<body>
    {% include "board/init.html" %}
    {% if user.is_authenticated %}

    <div class="jumbotron post-container main-content">
        <h1>Manage</h1>
        {% for information in infotext %}
        <span id="info-container"></span>
        <script>
            var element = document.getElementById('info-container');
            content = marked('{{ information.manage_contents }}');
            element.insertAdjacentHTML('afterbegin', content);
        </script>
        {% endfor %}
        <a class="btn btn-primary" href="push/" role="button"><strong>Push</strong> a new post</a>
    </div>


    {% else %}
    {% endif %}
</body>

{% include "board/footer.html" %}

</html>

board/templates/board/oof.html
<!doctype html>
<html class="no-js" lang="en-AU">

<!-- Find PotatoBoard at https://github.com/aidswidjaja/potatoboard-->
<!-- open source and everything under the MIT License! 2020-2021 (c) aidswidjaja -->

<head>
    <title>Oof | TYSK</title>
    {% include "board/head.html" %}
    <style>
        label {
            font-size: 1.2rem;
        }

        tr {
            border-top: 30px solid;
            border-bottom: 30px solid;
            border-color: transparent;
        }
    </style>
</head>

<body>
    {% include "board/init.html" %}

    <h1>Welp</h1>

    <p>You didn't use an email address domain that is permitted on the system. Try logging out below, then log back in again. (AuthForbidden at /complete/google-oauth2/ Your credentials aren't allowed)</p>
    <p><a class="btn btn-primary" href="/logout/">
        Log out
    </a></p>
</body>

{% include "board/footer.html" %}

</html>

board/templates/board/pipeline.html
<!doctype html>
<html class="no-js" lang="en-AU">

{% load static %}

<!-- Find PotatoBoard at https://github.com/aidswidjaja/potatoboard-->
<!-- open source and everything under the MIT License! 2020-2021 (c) aidswidjaja -->

<head>
    <title>Pipelining...</title>
    {% include "board/head.html" %}

    <style>
        body {
            margin: 5px;
        }
    </style>
</head>

<body>
    {% if user.is_authenticated %}

    <h1>Console output</h1>
    <div id="console">
        <samp>[Console] Begin logging.</samp>
        
    </div>

    <!-- declare template variables, die in DRY -->

    {{ post.title|json_script:"title" }}
    {{ post.subject|json_script:"subject" }}
    {{ post.get_subject_display|json_script:"get_subject_display" }}
    {{ post.content|json_script:"content" }}
    {{ post.channel|json_script:"channel" }}
    {{ post.important|json_script:"important" }}

    <script src="{% static 'env.js' %}"></script>
    <script src="{% static 'subjects.js' %}"></script>
    <script src="{% static 'pipeline.js' %}"></script>

    {% endif %}

</body>

</html>

board/templates/board/post.html
<!doctype html>
<html class="no-js" lang="en-AU">

<!-- Find PotatoBoard at https://github.com/aidswidjaja/potatoboard-->
<!-- open source and everything under the MIT License! 2020-2021 (c) aidswidjaja -->

<head>
    <title>{{ post.get_subject_display }} | TYSK</title>
    {% include "board/head.html" %}
</head>

<body>
    {% include "board/init.html" %}
    {% if user.is_authenticated %}
    <div class="jumbotron post-container">
        <h5>{{ post.get_subject_display }}</h5>
        <h6>
            {% if post.channel == "MAIN" %} <!-- quality DRY code -->
            <span class="badge badge-primary" style="background-color: #0070FF;">Main channel</span>
            {% endif %}
            {% if post.channel == "LOWP" %}
            <span class="badge badge-primary" style="background-color: #FFBE00; color: #000000;">Low
                priority</span>
            {% endif %}
            {% if post.channel == "META" %}
            <span class="badge badge-primary" style="background-color: #008A4F;">Meta update</span>
            {% endif %}
            {% if post.important %}
            <span class="badge badge-primary" style="background-color: #FF0000;">Important</span>
            {% endif %}
        </h6>
        <h5>{{ post.title }}</h5>
        <p id="post-content"></p>
        <h6>Location: {{ post.location }}</h6>
        <h6>Attachments: <a>https://{{ url }}/{{ post.file }}</a></h6>
        <h6>Published by {{ post.creator }} on {{ post.date_created }}<br>Last modified {{ post.date_created }}</h6>
        <div class="input-group">
            {% load static %}
            <script src="{% static 'init.js' %}"></script>
            <input class="form-control" id="clipboard-share" value="https://{{ url }}/{{ post.id }}/" readonly>
            <button class="btn btn-outline-secondary clipboard-handler" type="button" id="button-addon-2"
                data-clipboard-text="https://{{ url }}/{{ post.id }}/">Copy link&nbsp;<img
                    src="{% static 'copy.svg' %}"></span>
        </div>
    </div>
    <script>
        var element = document.getElementById('post-content');
        content = marked('{{ post.content|linebreaksbr }}');
        element.insertAdjacentHTML('beforeend', content);
    </script>
    {% else %}
    {% endif %}
</body>

{% include "board/footer.html" %}

</html>

board/templates/board/push.html
<!doctype html>
<html class="no-js" lang="en-AU">

<!-- Find PotatoBoard at https://github.com/aidswidjaja/potatoboard -->
<!-- open source and everything under the MIT License! 2020-2021 (c) aidswidjaja -->

<head>
    <title>Push a new post | TYSK</title>
    {% include "board/head.html" %}
    <style>
        label {
            font-size: 1.2rem;
        }

        tr {
            border-top: 30px solid;
            border-bottom: 30px solid;
            border-color: transparent;
        }
    </style>

</head>

<body>
    {% include "board/init.html" %}
    {% if user.is_authenticated %}

    <div class="jumbotron post-container main-content">
        <h2>Push a new post</h2>

        <form method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            {{ form.errors }}
            {{ form.non_field_errors }}
            <button type="submit">Submit</button>
        </form>
    </div>
    {% else %}
    {% endif %}
</body>

{% include "board/footer.html" %}

</html>